=== PGayol/sct-browser-frontend/REST/archive/concept_v2_schema.json
{
   "$schema":"http://json-schema.org/draft-04/schema#",
   "title":"conceptSchema",
   "type":"object",
   "properties":{
      "conceptId":{
         "type":"string"
      },
      "effectiveTime":{
         "type":"string"
      },
      "active":{
         "type":"boolean"
      },
      "moduleId":{
         "type":"string"
      },
      "definitionStatus":{
         "type":"object",
         "properties":{
            "preferredTerm":{
               "type":"string"
            },
            "conceptId":{
               "type":"string"
            }
         }
      },
      "fsn":{
         "type":"string"
      },
      "preferredTerm":{
         "type":"string"
      },
      "descriptions":{
         "type":"array",
         "items":{
            "type":"object",
            "properties":{
               "descriptionId":{
                  "type":"string"
               },
               "effectiveTime":{
                  "type":"string"
               },
               "active":{
                  "type":"boolean"
               },
               "moduleId":{
                  "type":"string"
               },
               "languageCode":{
                  "type":"string"
               },
               "type":{
                  "type":"object",
                  "properties":{
                     "preferredTerm":{
                        "type":"string"
                     },
                     "conceptId":{
                        "type":"string"
                     }
                  }
               },
               "term":{
                  "type":"string"
               },
               "caseSignificance":{
                  "type":"object",
                  "properties":{
                     "preferredTerm":{
                        "type":"string"
                     },
                     "conceptId":{
                        "type":"string"
                     }
                  }
               },
               "acceptabilityMap":{
                  "type":"array",
                  "items":{
                     "type":"object",
                     "properties":{
                        "languageReferenceSet":{
                           "type":"object",
                           "properties":{
                              "preferredTerm":{
                                 "type":"string"
                              },
                              "conceptId":{
                                 "type":"string"
                              }
                           }
                        },
                        "acceptability":{
                           "type":"object",
                           "properties":{
                              "preferredTerm":{
                                 "type":"string"
                              },
                              "conceptId":{
                                 "type":"string"
                              }
                           }
                        }
                     },
                     "required":[
                        "languageReferenceSet",
                        "acceptability"
                     ]
                  }
               }
            },
            "required":[
               "descriptionId",
               "effectiveTime",
               "active",
               "moduleId",
               "languageCode",
               "type",
               "term",
               "caseSignificance",
               "acceptabilityMap"
            ]
         }
      },
      "relationships":{
         "type":"array",
         "items":{
            "type":"object",
            "properties":{
               "relationshipId":{
                  "type":"string"
               },
               "effectiveTime":{
                  "type":"string"
               },
               "active":{
                  "type":"boolean"
               },
               "moduleId":{
                  "type":"string"
               },
               "sourceId":{
                  "type":"string"
               },
               "destination":{
                  "type":"object",
                  "properties":{
                     "conceptId":{
                        "type":"string"
                     },
                     "preferredTerm":{
                        "type":"string"
                     }
                  }
               },
               "relationshipGroup":{
                  "type":"number"
               },
               "type":{
                  "type":"object",
                  "properties":{
                     "conceptId":{
                        "type":"string"
                     },
                     "preferredTerm":{
                        "type":"string"
                     }
                  }
               },
               "characteristicTypeId":{
                  "type":"string"
               },
               "modifierId":{
                  "type":"string"
               }
            },
            "required":[
               "relationshipId",
               "effectiveTime",
               "active",
               "moduleId",
               "sourceId",
               "destination",
               "relationshipGroup",
               "type",
               "characteristicTypeId",
               "modifierId"
            ]
         }
      }
   }
}

=== PGayol/sct-browser-frontend/REST/archive/concept_v2.json
{
    "conceptId": "404684003",
    "effectiveTime": "20040131",
    "active": true,
    "moduleId": "900000000000207008",
    "definitionStatus": {
        "preferredTerm": "Primitive",
        "conceptId": "900000000000074008"
    },
    "fsn": "Clinical finding (finding)",
    "preferredTerm": "Clinical finding",
    "descriptions": [
        {
            "descriptionId": "2148514019",
            "effectiveTime": "20040131",
            "active": true,
            "moduleId": "900000000000207008",
            "languageCode": "en",
            "type": {
                "preferredTerm": "Fully specified name",
                "conceptId": "900000000000003001"
            },
            "term": "Clinical finding (finding)",
            "caseSignificance": {
                "preferredTerm": "Initial character case insensitive",
                "conceptId": "900000000000020002"
            },
            "acceptabilityMap": [
                {
                    "languageReferenceSet": {
                        "preferredTerm": "GB English",
                        "conceptId": "900000000000508004"
                    },
                    "acceptability": {
                        "preferredTerm": "Acceptable",
                        "conceptId": "900000000000549004"
                    }
                },
                {
                    "languageReferenceSet": {
                        "preferredTerm": "US English",
                        "conceptId": "900000000000509007"
                    },
                    "acceptability": {
                        "preferredTerm": "Acceptable",
                        "conceptId": "900000000000549004"
                    }
                }
            ]
        },
        {
            "descriptionId": "2148514019",
            "effectiveTime": "20040131",
            "active": true,
            "moduleId": "900000000000207008",
            "languageCode": "en",
            "type": {
                "preferredTerm": "Fully specified name",
                "conceptId": "900000000000003001"
            },
            "term": "Clinical finding",
            "caseSignificance": {
                "preferredTerm": "Initial character case insensitive",
                "conceptId": "900000000000020002"
            },
            "acceptabilityMap": [
                {
                    "languageReferenceSet": {
                        "preferredTerm": "GB English",
                        "conceptId": "900000000000508004"
                    },
                    "acceptability": {
                        "preferredTerm": "Acceptable",
                        "conceptId": "900000000000549004"
                    }
                },
                {
                    "languageReferenceSet": {
                        "preferredTerm": "US English",
                        "conceptId": "900000000000509007"
                    },
                    "acceptability": {
                        "preferredTerm": "Acceptable",
                        "conceptId": "900000000000549004"
                    }
                }
            ]
        }
    ],
    "relationships": [
        {
            "relationshipId": "2472459022",
            "effectiveTime": "20040131",
            "active": true,
            "moduleId": "900000000000207008",
            "sourceId": "404684003",
            "destination": {
                "conceptId": "138875005",
                "preferredTerm": "SNOMED CT Concept"
            },
            "relationshipGroup": 0,
            "type": {
                "conceptId": "116680003",
                "preferredTerm": "Is a"
            },
            "characteristicTypeId": "900000000000011006",
            "modifierId": "900000000000451002"
        },
        {
            "relationshipId": "4257218027",
            "effectiveTime": "20040131",
            "active": true,
            "moduleId": "900000000000207008",
            "sourceId": "404684003",
            "destination": {
                "conceptId": "138875005",
                "preferredTerm": "SNOMED CT Concept"
            },
            "relationshipGroup": 0,
            "type": {
                "conceptId": "116680003",
                "preferredTerm": "Is a"
            },
            "characteristicTypeId": "900000000000010007",
            "modifierId": "900000000000451002"
        }
    ]
}
